name: Publish to npm

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Enable Corepack
        run: corepack enable

      - name: Check Yarn version
        run: yarn --version

      - name: Set version in all package.json files
        run: |
          find . -name package.json -exec sed -i.bak "s/<VERSION>/${VERSION#v}/g" {} +

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn run build

      - name: Set NPM auth token
        run: npm config set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_PULUMI_PUBLISHER }}

      - name: Publish backend plugin
        run: yarn workspaces foreach -A --exclude @spacelift-io/backstage-plugins exec npm publish --access public
